<a href="https://colab.research.google.com/github/yromeking/Edwin_Data606/blob/main/ROW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -r requirements.txt
#!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 75.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 89.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 80.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.14.2
    Uninstalling statsmodels-0.14.2:
      Successfully uninstalled statsmodels-0.14.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 require

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
 import openai
 import os
 openai.api_key = 'sk-proj-JEmLSebyFhfrL6xG3ZHlT3BlbkFJOd4LnIEUGOm2E2J58oMA'

In [ ]:
#os.environ["OPENAI_API_KEY"] = api_key
os.environ["OPENAI_API_KEY"] = 'sk-proj-JEmLSebyFhfrL6xG3ZHlT3BlbkFJOd4LnIEUGOm2E2J58oMA'

In [ ]:
df= pd.read_excel('/content/Lottery_Powerball_Winning_Numbers__Beginning_2010.xlsx')

In [ ]:
df.head()

Date               Data
0 2020-09-26  11 21 27 36 62 24
1 2020-09-30  14 18 36 49 67 18
2 2020-10-03  18 31 36 43 47 20
3 2020-10-07  06 24 30 53 56 19
4 2020-10-10  05 18 23 40 50 18

In [ ]:
 df[['Col1', 'Col2','Col3','Col4', 'Col5','Col6']]= df['Data'].str.split(' ', expand=True)

In [ ]:
df.head()

Date               Data Col1 Col2 Col3 Col4 Col5 Col6
0 2020-09-26  11 21 27 36 62 24   11   21   27   36   62   24
1 2020-09-30  14 18 36 49 67 18   14   18   36   49   67   18
2 2020-10-03  18 31 36 43 47 20   18   31   36   43   47   20
3 2020-10-07  06 24 30 53 56 19   06   24   30   53   56   19
4 2020-10-10  05 18 23 40 50 18   05   18   23   40   50   18

In [ ]:
  df[['Data', 'Col2','Col3','Col4', 'Col5','Col6']] = df[['Col1', 'Col2','Col3','Col4', 'Col5','Col6']].astype(int)

In [ ]:
#read_file = pd.read_excel ("/content/Lottery_Powerball_Winning_Numbers__Beginning_2010.xlsx")

# Write the dataframe object
# into csv file
df[['Date', 'Data']].to_csv ("Timeseries_DJI.csv",
                  index = None,
                  header=True)


In [22]:
!python /content/next_seq_nr_value.py

Figure(640x480)
[15 21  5 12  8] - 3
[21  5 12  8  3] - 6
[ 5 12  8  3  6] - 7
[12  8  3  6  7] - 14
[ 8  3  6  7 14] - 5
[ 3  6  7 14  5] - 23
[ 6  7 14  5 23] - 8
[ 7 14  5 23  8] - 2
[14  5 23  8  2] - 10
[ 5 23  8  2 10] - 5
[23  8  2 10  5] - 1
[ 8  2 10  5  1] - 2
[ 2 10  5  1  2] - 29
[10  5  1  2 29] - 27
[ 5  1  2 29 27] - 4
[ 1  2 29 27  4] - 21
[ 2 29 27  4 21] - 1
[29 27  4 21  1] - 6
[27  4 21  1  6] - 5
[ 4 21  1  6  5] - 18
[21  1  6  5 18] - 30
[ 1  6  5 18 30] - 10
[ 6  5 18 30 10] - 24
[ 5 18 30 10 24] - 16
[18 30 10 24 16] - 21
[30 10 24 16 21] - 16
[10 24 16 21 16] - 15
[24 16 21 16 15] - 12
[16 21 16 15 12] - 4
[21 16 15 12  4] - 1
[16 15 12  4  1] - 3
[15 12  4  1  3] - 6
[12  4  1  3  6] - 2
[4 1 3 6 2] - 5
[1 3 6 2 5] - 6
[3 6 2 5 6] - 1
[6 2 5 6 1] - 6
[2 5 6 1 6] - 7
[5 6 1 6 7] - 2
[6 1 6 7 2] - 7
[1 6 7 2 7] - 1
[6 7 2 7 1] - 3
[7 2 7 1 3] - 6
[2 7 1 3 6] - 17
[ 7  1  3  6 17] - 9
[ 1  3  6 17  9] - 5
[ 3  6 17  9  5] - 8
[ 6 17  9  5  8] - 4
[17  9  5  8  4

In [ ]:
data.head()

Date  Data  Col2  Col3  Col4  Col5  Col6
0 2020-09-26    11    21    27    36    62    24
1 2020-09-30    14    18    36    49    67    18
2 2020-10-03    18    31    36    43    47    20
3 2020-10-07     6    24    30    53    56    19
4 2020-10-10     5    18    23    40    50    18